# Generated by Django 5.1.2 on 2025-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_logstatus_robotinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="logstatus",
            name="BehaviorStateComplete",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
