# Generated by Django 5.1.2 on 2025-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_logstatus_behaviorstatecomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='TeamMessageDecision',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
