# Generated by Django 5.1.2 on 2025-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_logstatus_audiodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='logstatus',
            name='WhistlePercept',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
