apiVersion: apps/v1
kind: Deployment
metadata:
  name: vat-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vat-frontend
  template:
    metadata:
      labels:
        app: vat-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/efcy/vite_frontend:latest
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      imagePullSecrets:
      - name: github-access
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config