apiVersion: v1
kind: Service
metadata:
  name: vat-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: vat-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: vat-frontend 