apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/external-secrets
    targetRevision: HEAD
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
