apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyte
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/flyte
    targetRevision: HEAD
    helm:
      releaseName: flyte
  destination:
    server: https://kubernetes.default.svc
    namespace: flyte
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
