apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/minio
    targetRevision: HEAD
    helm:
      releaseName: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
