apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: default
  source:
    repoURL: 'git@github.com:BerlinUnited/Visual-Analytics.git'
    path: deployment/redis
    targetRevision: HEAD
    helm:
      releaseName: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true