apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robotmanager
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/robotmanager
    targetRevision: HEAD
    helm:
      releaseName: robotmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: robotmanager
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true