apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/sealed-secrets
    targetRevision: HEAD
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
