apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vat-backend
spec:
  project: default
  source:
    repoURL: 'git@github.com:efcy/visual_analytics.git'
    path: deployment/vat-backend
    targetRevision: HEAD
    helm:
      releaseName: vat-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: vat-backend
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true