apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-fileserver
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-logs
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: logs.berlin-united.com
  dnsNames:
  - logs.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-logs
    kind: Issuer