apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-filesystem
  namespace: {{ .Values.namespace }}
  labels:
    app: log-filesystem
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($http_user_agent ~* (Googlebot|Google-InspectionTool|AdsBot-Google|Mediapartners-Google|Googlebot-Mobile|Googlebot-Image|Googlebot-Video|Googlebot-News|SemrushBot)) {
        return 403;
      }
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Supports-Loading-Mode "credentialed-prerender";
      add_header Cache-Control "public";
spec:
  ingressClassName: nginx
  rules:
    - host: "logs.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: logs-svc
                port:
                  number: 80
  tls:
  - hosts:
    - "logs.berlin-united.com"
    secretName: tls-cert-logs
