apiVersion: v2
name:  metaflow-minio
description: Metaflow Minio
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: minio
    repository: https://charts.min.io/
    version: 5.0.15
