apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-flyte
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-flyte
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: flyte.berlin-united.com
  dnsNames:
  - flyte.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-flyte
    kind: Issuer