apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-fileserver
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-backup
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: backup.berlin-united.com
  dnsNames:
  - backup.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-backup
    kind: Issuer