apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-grafana
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-grafana
  duration: 2160h
  renewBefore: 360h
  commonName: grafana.berlin-united.com
  dnsNames:
  - grafana.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-grafana
    kind: Issuer