# maybe the correct values yaml: https://github.com/bitnami/charts/blob/33b8e700bdecedd8e2130d442adc4593bb76816c/bitnami/postgresql/values.yaml
postgresql:
  auth:
    username: naoth
    database: vat
    existingSecret: postgres-secret
    secretKeys:
      adminPasswordKey: password
      userPasswordKey: password

  primary:
    pgHbaConfiguration: |
      local   all             postgres                              peer
      local   all             all                                   peer
      host    all             all             127.0.0.1/32          md5
      host    all             all             ::1/128               md5
    containerSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001

    extraEnvVars:
      - name: PGDATABASE
        value: vat
      - name: PGUSER
        value: postgres
# TODO: no persistence?