apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  # use the public ip address of the only k8s node
  - 141.20.26.37 - 141.20.26.37
      