apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-minio-console
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-minio-console
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: console.berlin-united.com
  dnsNames:
  - console.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-minio
    kind: Issuer