apiVersion: v2
name: flyte
description: flyte
type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
  - name: flyte-core
    repository: https://flyteorg.github.io/flyte-core
    version: 1.14.0