apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-api
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-api
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: api.berlin-united.com
  dnsNames:
  - api.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-api
    kind: Issuer