apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-vat
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-vat
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: vat.berlin-united.com
  dnsNames:
  - vat.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-vat
    kind: Issuer