apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vat-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: vat-backend
spec:
  ingressClassName: nginx
  rules:
    - host: "api.berlin-united.com"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-svc
                port:
                  number: 80
  tls:
  - hosts:
    - "api.berlin-united.com"
    secretName: tls-cert-api
