apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-rbac-cm
data:
  policy.csv: |
    {{- range .Values.custom.users }}
    g, {{ . }}, role:admin
    {{- end }}
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'



