apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: visual-analytics-repo
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: my-secret-store
  refreshInterval: "1m"
  target:
    creationPolicy: Owner
    deletionPolicy: "Retain"
  dataFrom:
    - extract:
        key: ArgoSSH
        property: type
    - extract:
        key: ArgoSSH
        property: url
    - extract:
        key: ArgoSSH
        property: sshPrivateKey