apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mlflow
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-mlflow
  duration: 2160h
  renewBefore: 360h
  commonName: mlflow.berlin-united.com
  dnsNames:
    - mlflow.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-mlflow
    kind: Issuer
