apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-rm
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-cert-rm
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: rm.berlin-united.com
  dnsNames:
  - rm.berlin-united.com
  issuerRef:
    name: letsencrypt-prod-rm
    kind: Issuer