apiVersion: v1
kind: Service
metadata:
  name: rm-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: robot-manager
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5247
      protocol: TCP
      name: http
  selector:
    app: robot-manager