name: Django CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd django
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
        VAT_POSTGRES_DB: postgres
        VAT_POSTGRES_USER: postgres
        VAT_POSTGRES_PASS: postgres
        VAT_POSTGRES_HOST: localhost
        VAT_POSTGRES_PORT: 5432
      run: |
        cd django
        pytest